apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-chat-config
  namespace: composer-ai-apps-demo
  labels:
    app.kubernetes.io/name: sample-chat
    app.kubernetes.io/component: config
data:
  OPENAI_DEFAULT_URL: https://vllm-composer-ai-apps.apps.cluster-nhsxz.nhsxz.sandbox1513.opentlc.com/v1
  OPENAI_DEFAULT_MODELNAME: vllm
  OPENAI_INSECURE_TLS: "0"
  BACKEND_URL: http://sample-chat-backend:8080
  NEXT_PUBLIC_APP_TITLE: Austin RHUG AI Chat
