apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-chat-config
  namespace: composer-ai-apps-demo
  labels:
    app.kubernetes.io/name: sample-chat
    app.kubernetes.io/component: config
data:
  OPENAI_DEFAULT_URL: https://integrate.api.nvidia.com/v1
  OPENAI_DEFAULT_MODELNAME: meta/llama-3.1-8b-instruct
  BACKEND_URL: http://sample-chat-backend:8080
  NEXT_PUBLIC_APP_TITLE: Austin RHUG AI Chat
