apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/part-of: austin-rhug-2016
spec:
  project: hello-world
  source:
    repoURL: https://github.com/dkypuros/austin_rhug_2016.git
    targetRevision: v0.1.0
    path: apps/hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
